name: Node CI

# Push tests pushes; PR tests merges
on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:
  runs-on: ubuntu-latest

  # Deploy the build
  deploy:
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Deploy build
        uses: beginner-corp/action-deploy@main
        with:
          begin_token: ${{ secrets.BEGIN_TOKEN }}
          log: 'debug'
          begin_args: '--sample arg'
