name: Node CI

# Push tests pushes; PR tests merges
on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:
  # Deploy the build
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Deploy build
        uses: beginner-corp/actions/deploy@testing
        with:
          begin_token: ${{ secrets.BEGIN_TOKEN }}
          log: 'debug'
          begin_args: '--sample arg'
